# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GridIntensity < Formula
  desc "Get carbon intensity data for electricity grids"
  homepage "https://github.com/thegreenwebfoundation/grid-intensity-go"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.4.0/grid-intensity_0.4.0_Darwin_arm64.tar.gz"
      sha256 "799a711dc43390b80b4f1081a8f8bab960c07869f17b67332dbf70eee8ed92f1"

      def install
        bin.install "grid-intensity"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.4.0/grid-intensity_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "bc407c94913ca0546ec7a60e9bc993fc9a05aa4b21cc10da691d457a4fbca223"

      def install
        bin.install "grid-intensity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.4.0/grid-intensity_0.4.0_Linux_x86_64.tar.gz"
      sha256 "5880de14045ca8098ad791d59878318eedb8ef24b763c8beb301cae91bb4c682"

      def install
        bin.install "grid-intensity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.4.0/grid-intensity_0.4.0_Linux_arm64.tar.gz"
      sha256 "e0bbf95e6954447620a5a6ba8ea9bfa8831349e79dad822394bef91eee7fffd8"

      def install
        bin.install "grid-intensity"
      end
    end
  end
end
