# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GridIntensity < Formula
  desc "Get carbon intensity data for electricity grids"
  homepage "https://github.com/thegreenwebfoundation/grid-intensity-go"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.7.0/grid-intensity_Darwin_x86_64.tar.gz"
      sha256 "44132d164a2dd04dfb476aefc7e0fc9fd876eb44e9b8f0f67b028f24bb295441"

      def install
        bin.install "grid-intensity"
      end
    end
    on_arm do
      url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.7.0/grid-intensity_Darwin_arm64.tar.gz"
      sha256 "e10ad586fa1cc20e1c80a60e355d8b527d61654787c61ff5ee33c6c599ea31af"

      def install
        bin.install "grid-intensity"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.7.0/grid-intensity_Linux_x86_64.tar.gz"
        sha256 "06d22c28a596682f8623de680e59f29c54eea1f3327b909d0c8414e875a4577f"

        def install
          bin.install "grid-intensity"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.7.0/grid-intensity_Linux_arm64.tar.gz"
        sha256 "b86ea830bae20723117cf4343eda8a40494deaa05ed04c9f49adc7417f29a6ac"

        def install
          bin.install "grid-intensity"
        end
      end
    end
  end
end
