# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GridIntensity < Formula
  desc "Get carbon intensity data for electricity grids"
  homepage "https://github.com/thegreenwebfoundation/grid-intensity-go"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.2.1/grid-intensity_0.2.1_Darwin_arm64.tar.gz"
      sha256 "f9a8fba0c2039b39338c69fbd7d1dbb94b54fabb9cf108a7172a20ec934361cc"

      def install
        bin.install "grid-intensity"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.2.1/grid-intensity_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "5bfa71b3853f7152849480d31fc45fc9610546c3df6e0da2e904f98303542d22"

      def install
        bin.install "grid-intensity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.2.1/grid-intensity_0.2.1_Linux_x86_64.tar.gz"
      sha256 "14526a0a0556c4a29d5cdde115b3a4802f790978670d5db15186c36703753a16"

      def install
        bin.install "grid-intensity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thegreenwebfoundation/grid-intensity-go/releases/download/v0.2.1/grid-intensity_0.2.1_Linux_arm64.tar.gz"
      sha256 "3dbfbb4104d983ceef20a72e615cd984360b4c50db7c0fceb7764485e52e3eae"

      def install
        bin.install "grid-intensity"
      end
    end
  end
end
